elements:
  - type: header
    paths:
      - //header
      - //nav[contains(@class, 'navbar')]
  - type: footer
    paths:
      - //footer
  - type: title
    paths:
      - //h1[text()]
      - //h2[text()]
      - //h3[text()]
      - //h4[text()]
      - //h5[text()]
      - //h6[text()]
  - type: text
    paths:
      - //p[text()]
      - //a[text()]
      - //strong[text()]
      - //small[text()]
      - //div[contains(@class, 'text-muted')]
      - //li[text()]
      - //label[text()]
    ignore:
      - //p[a[contains(@class, 'btn')]]
      - //strong[ancestor::p[text()]]
      - //small[ancestor::p[text()]]
      - //li[*[text()]]
      - //a[contains(@class, 'btn')]
      - //a[ancestor::p[text()]]
      - //a[contains(@class, 'dropdown-toggle')]
      - //a[@role = 'button']
      - //a[*[name()="svg"]]
      - //small[ancestor::h1[text()]]
      - //li[.//*[name()="svg"]]
  - type: nav-link
    paths:
      - //ul/li/a[text()]
      - //nav//a[text()]
      - //nav//a[contains(@class, 'nav-link')]
    ignore:
      - //ul/li/a[contains(@class, 'dropdown-toggle')]
  - type: image
    paths:
      - //img
      - //*[name()="svg"]
      - //*[name()="canvas"]
  - type: icon
    paths:
      - //*[name()="svg"]
  - type: text-field
    paths:
      - //input[@type = 'text']
      - //input[@type = 'password']
      - //input[@type = 'email']
      - //input[@type = 'search']
      - //input[@type = 'url']
  - type: checkbox
    paths:
      - //input[@type = 'checkbox']
  - type: radio
    paths:
      - //input[@type = 'radio']
  - type: button
    paths:
      - //button
      - //a[contains(@class, 'btn')]
  - type: dropdown
    paths:
      - //select
      - //a[contains(@class, 'dropdown-toggle')]
fonts:
  - "'Indie Flower', cursive"
  - "'Kalam', cursive"
  - "'Amatic SC', cursive"
  - "'Shadows Into Light', cursive"
  - "'Caveat', cursive"
  - "'Caveat Brush', cursive"
  - "'Nothing You Could Do', cursive"
keepOriginalText: true
randomize: true
randomOffset: 5
options:
  roughness: 1.3
  bowing: 5
  strokeWidth: 1.5
  hachureGap: 4

