elements:
  - type: Header
    paths:
      - //header
      - //nav[contains(@class, 'navbar')]
    css: css.height > 0 && css.width > 0
  - type: Footer
    paths:
      - //footer
    css: css.height > 0 && css.width > 0
  - type: Text
    paths:
      - //div[text() and not(./*)]
      - //p[text()[normalize-space()]]
      - //a[text()[normalize-space()]]
      - //strong[text() and not(ancestor::p[text()])]
      - //small[text() and not(./*)]
      - //div[contains(@class, 'text-muted') and not(./*) and text()]
      - //ul/li[text() and not(./*)]
      - //ul/li[not(normalize-space(text())='') and ./*]
      - //ul/li[*/following-sibling::text()[not(normalize-space(.)='')]]
      - //ol/li[text() and not(./*)]
      - //ol/li[not(normalize-space(text())='') and ./*]
      - //ol/li[*/following-sibling::text()[not(normalize-space(.)='')]]
      - //label[text()[normalize-space()]]
      - //span[text() and not(./*)]
      - //span[text()[normalize-space()] and span and count(span) = count(*)]
      - //span[text()[normalize-space()] and a and count(a) = count(*)]
      - //span[text()[normalize-space()] and a and span and count(a) + count(span) = count(*)]
      - //div[contains(@class, 'small') and not(./*) and text()]
      - //footer/*[text() and not(./*)]
      - //dd[text()[normalize-space()] and not(./*)]
      - //blockquote[text()]
      - //th[text() and not(./*)]
      - //td[text() and not(./*)]
      - //div[contains(@class, 'lia-truncated-body-container') and text()]
    ignore:
      - //p[a[contains(@class, 'btn')]]
      - //strong[ancestor::p[text()]]
      - //small[ancestor::p[text()]]
      - //a[contains(@class, 'btn')]
      - //a[ancestor::p[text()] or ancestor::label[text()] or ancestor::span[text()] or ancestor::strong[text()]]
      - //a[ancestor::p[text()] or ancestor::label[text()] or ancestor::span[text()] or ancestor::strong[text()]]/span
      - //a[contains(@class, 'dropdown-toggle') or @data-toggle="dropdown"]
      - //a[contains(@class, 'dropdown-toggle') or @data-toggle="dropdown"]/*
      - //a[@role = 'button']
      - //a[not(text()[normalize-space()]) and (*[name()="svg"] or img)]
      - //strong[ancestor::h1 or ancestor::h2 or ancestor::h3 or ancestor::h4 or ancestor::h5 or ancestor::h6]
      - //small[ancestor::h1[text()]]
      - //a[ancestor::h1 or ancestor::h2 or ancestor::h3 or ancestor::h4 or ancestor::h5 or ancestor::h6]
      - //a[./h1 or ./h2 or ./h3 or ./h4 or ./h5 or ./h6 or ./i]
      - //ul/li[not(normalize-space(text())='') and ./*]/a
      - //ul/li[not(normalize-space(text())='') and ./*]/strong
      - //ul/li[text() and not(./*) and string-length(text()) < 2]
      - //ol/li[not(normalize-space(text())='') and ./*]/a
      - //ol/li[not(normalize-space(text())='') and ./*]/strong
      - //ol/li[text() and not(./*) and string-length(text()) < 2]
      - //span[ancestor::button or ancestor::a[text()[normalize-space()]] or ancestor::p[text()[normalize-space()]] or ancestor::label[text()] or (string-length(text()) < 2 and not(number(text())))]
      - //*[contains(@class, 'sr-only') or ancestor::*[contains(@class, 'sr-only') ]]
      - //figure//*
      - //p[button and count(button) = count(*)]
      - //*[ancestor::pre]
      - //div[contains(@class, 'lia-truncated-body-container') and text()]/a
    css: css.font_size > 0
  - type: Title
    paths:
      - //h1[.//text()]
      - //h2[.//text()]
      - //h3[.//text()]
      - //h4[.//text()]
      - //h5[.//text()]
      - //h6[.//text()]
      - //span[text() and (not(./*) or *[not(text())]) and (ancestor::h1 or ancestor::h2 or ancestor::h3 or ancestor::h4 or ancestor::h5 or ancestor::h6)]
    ignore:
      - //h1[not(text()) and span[text() and (not(./*) or *[not(text())])]]
      - //h2[not(text()) and span[text() and (not(./*) or *[not(text())])]]
      - //h3[not(text()) and span[text() and (not(./*) or *[not(text())])]]
      - //h4[not(text()) and span[text() and (not(./*) or *[not(text())])]]
      - //h5[not(text()) and span[text() and (not(./*) or *[not(text())])]]
      - //h6[not(text()) and span[text() and (not(./*) or *[not(text())])]]
      - //span[ancestor::h1[text()] or ancestor::h2[text()] or ancestor::h3[text()] or ancestor::h4[text()] or ancestor::h5[text()] or ancestor::h6[text()]]
  - type: Link
    paths:
      - //ul/li[normalize-space(text())='' and count(*)=1]/a[text() and (not(./*) or *[not(text())])]
      - //ol/li[normalize-space(text())='' and count(*)=1]/a[text() and (not(./*) or *[not(text())])]
      - //nav//a[text()]
      - //nav//a[contains(@class, 'nav-link') and text()]
      - //header//a[text() and not(./*)]
    ignore:
      - //ul/li/a[contains(@class, 'dropdown-toggle')]
      - //ol/li/a[contains(@class, 'dropdown-toggle')]
      - //ul/li[a/following-sibling::text()[not(normalize-space(.)='')]]/a
  - type: Image
    paths:
      - //img
      - //*[name()='svg']
      - //*[name()='canvas']
      - //i
      - //div[contains(@style, 'background-image')]
      - //section[contains(@style, 'background-image')]
      - //figure[*]
      - //iframe
      - //video
    ignore:
      - //i[ancestor::p[text()]]
      - //img[ancestor::input]
      - //*[ancestor::iframe]
      - //img[ancestor::label]
      - //img[ancestor::h1[text()] or ancestor::h2[text()] or ancestor::h3[text()] or ancestor::h4[text()] or ancestor::h5[text()] or ancestor::h6[text()]]
  - type: Icon
    paths:
      - //*[name()="svg" and @width <= 40 and @height <= 40 and count(*[not(name()="use")]) > 0]
    ignore:
      - //*[name() = 'svg' and (ancestor::h1[text()] or ancestor::h2[text()] or ancestor::h3[text()] or ancestor::h4[text()] or ancestor::h5[text()] or ancestor::h6[text()])]
      - //*[name() = 'svg' and ancestor::span[text()]]
      - //*[(name() = 'svg' or img) and ancestor::a[text()[normalize-space()]]]
  - type: Container
    paths:
      - //div[.//text() and ./*]
      - //a[text() and ./*]
    ignore:
      - //a[contains(@class, 'dropdown-toggle') or @data-toggle="dropdown"]
    css: css.border_bottom_width > 0 && css.border_left_width > 0 && css.border_right_width > 0 && css.border_top_width > 0
  - type: TextField
    paths:
      - //input[@type = 'text']
      - //input[@type = 'password']
      - //input[@type = 'email']
      - //input[@type = 'search']
      - //input[@type = 'url']
      - //input[@type = 'tel']
      - //textarea
    css: css.height > 0 && css.width > 0
  - type: Checkbox
    paths:
      - //input[@type = 'checkbox']
  - type: Radio
    paths:
      - //input[@type = 'radio']
  - type: Button
    paths:
      - //button
      - //a[contains(@class, 'btn')]
      - //input[contains(@class, 'btn')]
      - //span[contains(@class, 'btn')]
    ignore:
      - //*[contains(@class, 'btn-group')]
      - //button[count(*[not(name() = 'svg' or img or i)]) > 0]
  - type: Burger
    paths:
      - //button[@aria-label = 'Toggle navigation' and contains(@class, 'navbar-toggler')]
  - type: Dropdown
    paths:
      - //select
      - //a[contains(@class, 'dropdown-toggle') and not(ancestor::li)]
      - //li[.//*[contains(@class, 'dropdown-menu')]]
browser: chrome
headless: true
window:
  height: 960
  width: 1536
