elements:
  - type: Container
    paths:
      - //div[text()]
    css: css.border_bottom_width > 0 && css.border_left_width > 0 && css.border_right_width > 0 && css.border_top_width > 0
  - type: Header
    paths:
      - //header
      - //nav[contains(@class, 'navbar')]
    css: css.height > 0 && css.width > 0
  - type: Footer
    paths:
      - //footer
    css: css.height > 0 && css.width > 0
  - type: Text
    paths:
      - //p[text()]
      - //a[text()]
      - //strong[text() and not(ancestor::p[text()])]
      - //small[text()]
      - //div[contains(@class, 'text-muted')]
      - //ul/li[text() and not(./*)]
      - //ul/li[not(normalize-space(text())='') and ./*]
      - //label[text()]
      - //span[text() and not(./*)]
    ignore:
      - //p[a[contains(@class, 'btn')]]
      - //strong[ancestor::p[text()]]
      - //small[ancestor::p[text()]]
      - //a[contains(@class, 'btn')]
      - //a[ancestor::p[text()]]
      - //a[contains(@class, 'dropdown-toggle')]
      - //a[@role = 'button']
      - //a[*[name()="svg"]]
      - //small[ancestor::h1[text()]]
      - //a[ancestor::h1 or ancestor::h2 or ancestor::h3 or ancestor::h4 or ancestor::h5 or ancestor::h6]
      - //ul/li[not(normalize-space(text())='') and ./*]/a
      - //ul/li[not(normalize-space(text())='') and ./*]/strong
      - //ul/li[text() and not(./*) and string-length(text()) < 2]
      - //span[ancestor::button or ancestor::a or ancestor::label or string-length(text()) < 2]
  - type: Title
    paths:
      - //h1[.//text()]
      - //h2[.//text()]
      - //h3[.//text()]
      - //h4[.//text()]
      - //h5[.//text()]
      - //h6[.//text()]
      - //span[text() and not(./*) and (ancestor::h1 or ancestor::h2 or ancestor::h3 or ancestor::h4 or ancestor::h5 or ancestor::h6)]
    ignore:
      - //h1[not(text()) and span[text() and not(./*)]]
      - //h2[not(text()) and span[text() and not(./*)]]
      - //h3[not(text()) and span[text() and not(./*)]]
      - //h4[not(text()) and span[text() and not(./*)]]
      - //h5[not(text()) and span[text() and not(./*)]]
      - //h6[not(text()) and span[text() and not(./*)]]
      - //span[ancestor::h1[text()] or ancestor::h2[text()] or ancestor::h3[text()] or ancestor::h4[text()] or ancestor::h5[text()] or ancestor::h6[text()]]
  - type: Link
    paths:
      - //ul/li[normalize-space(text())='' and count(*)=1]/a[text()]
      - //nav//a[text()]
      - //nav//a[contains(@class, 'nav-link') and text()]
      - //header//a[text() and not(./*)]
    ignore:
      - //ul/li/a[contains(@class, 'dropdown-toggle')]
  - type: Image
    paths:
      - //img
      - //*[name()='svg']
      - //*[name()='canvas']
      - //i
      - //div[contains(@style, 'background-image')]
  - type: Icon
    paths:
      - //*[name()="svg" and @width <= 50]
  - type: TextField
    paths:
      - //input[@type = 'text']
      - //input[@type = 'password']
      - //input[@type = 'email']
      - //input[@type = 'search']
      - //input[@type = 'url']
  - type: Checkbox
    paths:
      - //input[@type = 'checkbox']
  - type: Radio
    paths:
      - //input[@type = 'radio']
  - type: Button
    paths:
      - //button
      - //a[contains(@class, 'btn')]
  - type: Burguer
    paths:
      - //button[@aria-label = 'Toggle navigation' and contains(@class, 'navbar-toggler')]
  - type: Dropdown
    paths:
      - //select
      - //a[contains(@class, 'dropdown-toggle')]
browser: chrome
headless: true
window:
  height: 960
  width: 1536
