elements:
  - type: Container
    paths:
      - //div[text() and *]
  - type: Header
    paths:
      - //header
      - //nav[contains(@class, 'navbar')]
  - type: Footer
    paths:
      - //footer
  - type: Title
    paths:
      - //h1[.//text()]
      - //h2[.//text()]
      - //h3[.//text()]
      - //h4[.//text()]
      - //h5[.//text()]
      - //h6[.//text()]
  - type: Text
    paths:
      - //p[text()]
      - //a[text()]
      - //strong[text()]
      - //small[text()]
      - //div[contains(@class, 'text-muted')]
      - //li[text()]
      - //label[text()]
    ignore:
      - //p[a[contains(@class, 'btn')]]
      - //strong[ancestor::p[text()]]
      - //small[ancestor::p[text()]]
      - //li[*[text()]]
      - //a[contains(@class, 'btn')]
      - //a[ancestor::p[text()]]
      - //a[contains(@class, 'dropdown-toggle')]
      - //a[@role = 'button']
      - //a[*[name()="svg"]]
      - //small[ancestor::h1[text()]]
      - //li[.//*[name()="svg"]]
      - //a[ancestor::h1 or ancestor::h2 or ancestor::h3 or ancestor::h4 or ancestor::h5 or ancestor::h6]
  - type: Link
    paths:
      - //ul/li/a[text()]
      - //nav//a[text()]
      - //nav//a[contains(@class, 'nav-link')]
    ignore:
      - //ul/li/a[contains(@class, 'dropdown-toggle')]
  - type: Image
    paths:
      - //img
      - //*[name()='svg']
      - //*[name()='canvas']
  - type: Icon
    paths:
      - //*[name()="svg" and @width <= 50]
  - type: TextField
    paths:
      - //input[@type = 'text']
      - //input[@type = 'password']
      - //input[@type = 'email']
      - //input[@type = 'search']
      - //input[@type = 'url']
  - type: Checkbox
    paths:
      - //input[@type = 'checkbox']
  - type: Radio
    paths:
      - //input[@type = 'radio']
  - type: Button
    paths:
      - //button
      - //a[contains(@class, 'btn')]
  - type: Burguer
    paths:
      - //button[@aria-label = 'Toggle navigation' and contains(@class, 'navbar-toggler')]
  - type: Dropdown
    paths:
      - //select
      - //a[contains(@class, 'dropdown-toggle')]
keepOriginalText: true
